In [1]:
import pandas as pd

In [3]:
ab = pd.read_csv("../data/cookie_cats.csv")
print(len(ab))
print(ab['version'].value_counts())
ab.head()

90189
version
gate_40    45489
gate_30    44700
Name: count, dtype: int64

   userid  version  sum_gamerounds  retention_1  retention_7
0     116  gate_30               3        False        False
1     337  gate_30              38         True        False
2     377  gate_40             165         True        False
3     483  gate_40               1        False        False
4     488  gate_40             179         True         True

In [5]:
summary = ab.groupby('version')['retention_7'].agg(['mean','sum','count'])
summary

             mean   sum  count
version
gate_30  0.190201  8502  44700
gate_40  0.182000  8279  45489

In [10]:
r30 = ab.loc[ab["version"] == "gate_30", "retention_7"].mean()
r40 = ab.loc[ab["version"] == "gate_40", "retention_7"].mean()
print(f"gate_30 (контроль): {r30:.5f}  ({r30:.3%})")
print(f"gate_40 (вариант):  {r40:.4f}  ({r40:.2%})")
print(f"Разница: {(r40 - r30):.2%}")

gate_30 (контроль): 0.19020  (19.020%)
gate_40 (вариант):  0.1820  (18.20%)
Разница: -0.82%

In [12]:
from statsmodels.stats.proportion import proportions_ztest

In [14]:
returned = ab.groupby('version')['retention_7'].sum()
returned

version
gate_30    8502
gate_40    8279
Name: retention_7, dtype: int64

In [16]:
totals = ab.groupby('version')['retention_7'].count()
totals

version
gate_30    44700
gate_40    45489
Name: retention_7, dtype: int64

In [19]:
count = [returned["gate_30"], returned["gate_40"]]
nobs  = [totals["gate_30"],  totals["gate_40"]]
print(count)
print(nobs)

[np.int64(8502), np.int64(8279)]
[np.int64(44700), np.int64(45489)]

In [20]:
z_stat, p_value = proportions_ztest(count,nobs)

In [21]:
print(f"Вернулись:  gate_30 = {count[0]:,} из {nobs[0]:,}")
print(f"            gate_40 = {count[1]:,} из {nobs[1]:,}")
print(f"z-статистика: {z_stat:.3f}")
print(f"p-value:      {p_value:.4f}")

Вернулись:  gate_30 = 8,502 из 44,700
            gate_40 = 8,279 из 45,489
z-статистика: 3.164
p-value:      0.0016

In [23]:
ret1 = ab.groupby('version')['retention_1'].sum()
ret1

version
gate_30    20034
gate_40    20119
Name: retention_1, dtype: int64

In [24]:
tot1 = ab.groupby('version')['retention_1'].count()
tot1

version
gate_30    44700
gate_40    45489
Name: retention_1, dtype: int64

In [25]:
cou1 = [ret1['gate_30'],ret1['gate_40']]
nobs1 = [tot1['gate_30'],tot1['gate_40']]

In [26]:
z,p = proportions_ztest(cou1,nobs1)

In [28]:
print(f"z-статистика: {z:.3f}")
print(f"p-value       {p:.4f}")

z-статистика: 1.784
p-value       0.0744